apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
    scrape_configs:
      - job_name: 'portal-metrics'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['portal-service.portal:5000']
