apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portal-rolebinding-portal
  namespace: portal
subjects:
  - kind: ServiceAccount
    name: portal-sa
    namespace: portal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: portal-role
