apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: dungeon-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        env:
          - name: GF_SECURITY_ALLOW_EMBEDDING
            value: "true"
          - name: GF_PANELS_DISABLE_SANITIZE_HTML
            value: "true"
          - name: GF_INSTALL_PLUGINS
            value: "yesoreyeram-infinity-datasource"
          - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
            value: "/var/lib/grafana/dashboards/dashboard.json"
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "pass"
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: true
          - name: dashboard-config
            mountPath: /var/lib/grafana/dashboards
          - name: provisioning-config
            mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-config
          configMap:
            name: grafana-dashboard-config
        - name: provisioning-config
          configMap:
            name: grafana-dashboard-provisioning